---
- name: Add apt repositories
  become: true
  become_user: root
  with_items: '{{ zfs_apt_repos }}'
  ansible.builtin.apt_repository:
    repo: '{{ item }}'
    state: present

- name: Pining packages...
  become: true
  become_user: root
  with_items: '{{ zfs_pins | default([]) }}'
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '644'
