---
- name: add apt repositories
  become: true
  become_user: root
  with_items: '{{ zfs_apt_repos }}'
  apt_repository:
    repo: '{{ item }}'
    state: present

- name: pining packages...
  become: true
  become_user: root
  with_items: '{{ zfs_pins | default([]) }}'
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: 0644
